version: '3.4'

services:

  webapi:
    container_name: nopaper-legislativo-api
    image: nopaper-legislativo-api
    build:
      context: .
      dockerfile: src/Agape.NoPaper.Api/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mssql

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: nopaper-legislativo-mssql
    environment:
      SA_PASSWORD: "#Agape@2020"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433